# Numpy

NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays<br>
Numpy is a very important tool for scientific computing, allowing user to easily work on multi-dimensional data. It also contains useful mathematic functions including random sampling, trgionometric functions etc.

To start working with numpy, import numpy using

In [1]:
import numpy as np

np is the most common abbreviation used for numpy.<br>
Now that numpy is loaded, we can use its functions.

# 1. Array, Matrices and Tensors

numpy can convert a list to array, or it can generate points or can fill with constant numbers.

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
# Generate 40 points between 10 and 20
np.linspace(10,20, num=40)

array([10.        , 10.25641026, 10.51282051, 10.76923077, 11.02564103,
       11.28205128, 11.53846154, 11.79487179, 12.05128205, 12.30769231,
       12.56410256, 12.82051282, 13.07692308, 13.33333333, 13.58974359,
       13.84615385, 14.1025641 , 14.35897436, 14.61538462, 14.87179487,
       15.12820513, 15.38461538, 15.64102564, 15.8974359 , 16.15384615,
       16.41025641, 16.66666667, 16.92307692, 17.17948718, 17.43589744,
       17.69230769, 17.94871795, 18.20512821, 18.46153846, 18.71794872,
       18.97435897, 19.23076923, 19.48717949, 19.74358974, 20.        ])

For matrices, we can reshape an array, convert list of list to matrices or can fill constant value in the given sape (dimension).

In [4]:
np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
# linear array
x = np.array([1,2,3,4])
# convert to 2*2 matrix
x.reshape(2,2)

array([[1, 2],
       [3, 4]])

Here (2,2) is the shape for that numpy array. To get the shape of any array

In [6]:
a = np.array([[1,2,3], [4,5,6]])
print(a.shape)

(2, 3)


To fill with constant values such as 0, 1 etc

In [10]:
print(np.zeros((2,4)))
print(np.ones((3,2)))
# replace 5 with any value
print(np.full((3,3), 5))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[5 5 5]
 [5 5 5]
 [5 5 5]]


Shape can be of any dimension. Numpy can also store tensors which are basically matrices with more dimensions.

In [11]:
tensor = np.ones((2,3,4))
print(tensor)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


# 2. Mathematical Operations

Numpy supports various mathematical operations on single value as well as tensors (including arrays and matrices).

In [12]:
print(np.cos(0))
print(np.log(100))

1.0
4.605170185988092


In [13]:
a = np.array([[1,np.pi], [2,3]])

print(np.cos(a))
print(np.log(a))

[[ 0.54030231 -1.        ]
 [-0.41614684 -0.9899925 ]]
[[0.         1.14472989]
 [0.69314718 1.09861229]]


All type of matrix operations are also supported.

In [14]:
a = np.ones((2,3))
b = np.full((2,3), 4)

# element wise
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[[5. 5. 5.]
 [5. 5. 5.]]
[[-3. -3. -3.]
 [-3. -3. -3.]]
[[4. 4. 4.]
 [4. 4. 4.]]
[[0.25 0.25 0.25]
 [0.25 0.25 0.25]]


In [15]:
# Inverse of matrix
b_inv = b.T
print(b_inv)

# Matrix multiplication - a * b_inv
print(a.dot(b_inv))

[[4 4]
 [4 4]
 [4 4]]
[[12. 12.]
 [12. 12.]]


Even operations with scalar and vector are also supported

In [16]:
print(a * np.pi)

[[3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265]]


Other operations

In [19]:
print(np.sqrt(b))
print(b ** 2) # element wise square

[[2. 2. 2.]
 [2. 2. 2.]]
[[16 16 16]
 [16 16 16]]


# 3. Random Sampling

Array of given shape, filled with rando, numbers

In [20]:
print(np.random.rand(2,3))

[[0.74568988 0.59826031 0.80932891]
 [0.237936   0.5055867  0.31938289]]


Other useful distributions

In [21]:
# Normal distribution with mean=5 and stddev=2
dist = np.random.normal(5, 2, (9,9))

print(dist)

[[ 2.39799349  7.27108809  0.71682675  4.49497295  3.49860718  4.76293964
   4.89499179  2.99750722  3.94242338]
 [ 3.74228633  7.35626069  8.06436006  4.56980949  3.89796028  4.62476777
   6.42975532  4.17591469  5.53110481]
 [ 6.65897783 -0.29126636  5.93217668  7.78524254  7.75994707  4.11460938
   2.97753656  4.20143763  2.88400658]
 [ 3.85464282  6.67758475  3.57341406  6.78443936  6.02566168  5.5808173
   4.81388565  3.08904667  4.21374703]
 [ 5.21726933  4.93880282  6.06455149  4.1540008   7.39305949  7.51585811
   1.55465506  7.65793066  7.21841948]
 [ 2.28283399  4.98535744  0.1170256   3.66937327  2.75955562  5.20779521
   1.87702956  4.42251352  5.53536013]
 [ 5.7393484   3.97508897  1.38373483  6.17405754  4.93066965  3.94065833
   6.315093    6.22100708  1.54771562]
 [ 5.88888045  2.809383    6.23289526  6.76003328  0.58686263  5.31402971
   7.8353773   4.6507621   3.33571932]
 [ 5.45029259  4.12788165  1.63642283  4.17413391  3.02628532  5.97895955
   6.50376712  7.640271

Statistical measurements

In [23]:
data = np.random.rand(4,5)

print(np.mean(data)) # mean
print(np.var(data)) # variance

0.5087981467249536
0.08498896315659359


# 4. Indexing and Slicing

Operating on higher dimensional data requires advanced indexing and slicing methods.

In [26]:
# A tensor with shape (3, 4, 2)

t = np.random.rand(3, 4, 2)
print(t)

# selecting first element at 0,0,0
print(t[0,0,0])

# selecting element at 1,2,0
print(t[1,2,0])

[[[0.26820136 0.2257293 ]
  [0.10780807 0.70646175]
  [0.14114978 0.33340541]
  [0.00914399 0.97083635]]

 [[0.53161623 0.68690143]
  [0.01584559 0.67169812]
  [0.73430523 0.17145588]
  [0.58617776 0.5051056 ]]

 [[0.88543992 0.72093518]
  [0.17064674 0.03807685]
  [0.53583513 0.14245991]
  [0.84060044 0.82172754]]]
0.2682013593994662
0.734305234706431


In [27]:
# selecting entire matrix at position 1 in the first dimension
print(t[1])

# selecting vector at position 1,2 for the first two dimensions
print(t[1,2])

[[0.53161623 0.68690143]
 [0.01584559 0.67169812]
 [0.73430523 0.17145588]
 [0.58617776 0.5051056 ]]
[0.73430523 0.17145588]


Numpy supports python like ' : ' based slicing

In [28]:
# selecting first two row of first dimension
print(t[:2])

[[[0.26820136 0.2257293 ]
  [0.10780807 0.70646175]
  [0.14114978 0.33340541]
  [0.00914399 0.97083635]]

 [[0.53161623 0.68690143]
  [0.01584559 0.67169812]
  [0.73430523 0.17145588]
  [0.58617776 0.5051056 ]]]


In [30]:
# combining slicing for multiple dimensions
print(t[:2, :-1, :])

[[[0.26820136 0.2257293 ]
  [0.10780807 0.70646175]
  [0.14114978 0.33340541]]

 [[0.53161623 0.68690143]
  [0.01584559 0.67169812]
  [0.73430523 0.17145588]]]


Replacing a column with some value

In [31]:
# replacing 2nd dimension of t with first and last index of 1 with 0
t[1, :, 1] = 0
print(t)

[[[0.26820136 0.2257293 ]
  [0.10780807 0.70646175]
  [0.14114978 0.33340541]
  [0.00914399 0.97083635]]

 [[0.53161623 0.        ]
  [0.01584559 0.        ]
  [0.73430523 0.        ]
  [0.58617776 0.        ]]

 [[0.88543992 0.72093518]
  [0.17064674 0.03807685]
  [0.53583513 0.14245991]
  [0.84060044 0.82172754]]]


These indexes and axis (dimension) can be used for many functions.<br>
For example adding values in the given axis

In [32]:
# Summing the last axis and replcaing it with the sum
print(t.sum(axis=-1))

[[0.49393066 0.81426982 0.47455519 0.97998035]
 [0.53161623 0.01584559 0.73430523 0.58617776]
 [1.60637509 0.20872359 0.67829503 1.66232798]]
