## NumPy Basics

In [2]:
import numpy as np

In [16]:
a = np.array([1,2,3,4,5])
print(a)
print(a[1])

[1 2 3 4 5]
2


In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [5]:
print(a.shape)

(5,)


In [6]:
b = np.array([
    [1,2],
    [2,3],
    [3,4],
    [4,5]
])

print(b)
print(b.shape)

[[1 2]
 [2 3]
 [3 4]
 [4 5]]
(4, 2)


In [12]:
print(b.shape) # 4 X 2 matrix
print(b.size) # 4*2
print(b.dtype)
print(b.ndim) # Number of axes of the array

(4, 2)
8
int64
2


In [15]:
print(b)
print(b[0][0])
print(b[0][1])

[[1 2]
 [2 3]
 [3 4]
 [4 5]]
1
2


In [23]:
# We can specify the dtype

arr = np.array([1,2,3],dtype=float)
print(arr)

arr = np.array([2,3,4],dtype=complex)
print(arr)

arr = np.array([
    [1,2],
    [2,3]
],dtype=np.int16)
print(arr)



[1. 2. 3.]
[2.+0.j 3.+0.j 4.+0.j]
[[1 2]
 [2 3]]


In [25]:
# Create array of zeroes and ones, custom array

a = np.zeros((3,3))
print(a)

a = np.zeros((3,3),dtype=np.int64)
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [26]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [29]:
# Array of some constants
a = np.full((3,4),5)
print(a)

a = np.full((3,4),5,dtype=float)
print(a)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]


In [30]:
# Identity Matrix -> square matrix
a = np.eye(4)
print(a)

a = np.eye(4,dtype=int)
print(a)



[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [31]:
# Random Matrix
randomMatrix = np.random.random((2,3))
print(randomMatrix)

[[0.88715599 0.56360729 0.93305416]
 [0.27754212 0.1951297  0.0973809 ]]


In [33]:
a = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [34]:
print(a[1][2])

7


In [35]:
print(a[1:3,1:3])

[[ 6  7]
 [10 11]]


In [36]:
print(a[2,1:])
print(a[2,1:4])

[10 11 12]
[10 11 12]


In [37]:
a = np.zeros((3,3))
print(a)

a[ : ,-1] = 7
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 7.]
 [0. 0. 7.]
 [0. 0. 7.]]


In [38]:
a[1,:] = 8
print(a)

[[0. 0. 7.]
 [8. 8. 8.]
 [0. 0. 7.]]


In [39]:
# Mathematical Operations

x = np.array([
    [1,2],
    [2,3]
])
y = np.array([
    [4,5],
    [5,6]
])

# Element wise operations

print(x+y)
print(np.add(x,y))
print(x-y)
print(np.subtract(x,y))
print(x*y)
print(np.multiply(x,y))
print(x/y)
print(np.divide(x,y))

[[5 7]
 [7 9]]
[[5 7]
 [7 9]]
[[-3 -3]
 [-3 -3]]
[[-3 -3]
 [-3 -3]]
[[ 4 10]
 [10 18]]
[[ 4 10]
 [10 18]]
[[0.25 0.4 ]
 [0.4  0.5 ]]
[[0.25 0.4 ]
 [0.4  0.5 ]]


In [40]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.41421356 1.73205081]]


In [41]:
# Matrix Multiplications and dot products
print(x)
print(y)

[[1 2]
 [2 3]]
[[4 5]
 [5 6]]


In [42]:
# Matrix multiplication
print(x.dot(y))
print(np.dot(x,y))

[[14 17]
 [23 28]]
[[14 17]
 [23 28]]


In [43]:
# dot of vectors

a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

print(a.dot(b))
print(np.dot(a,b))

40
40


In [44]:
print(a)
print(sum(a))
print(np.sum(a))

[1 2 3 4]
10
10


In [47]:
print(x)

[[1 2]
 [2 3]]


In [48]:
print(sum(x)) # equivalent to np.sum(x,axis=1)

[3 5]


In [49]:
np.sum(x)

8

In [50]:
np.sum(x,axis=0)

array([3, 5])

In [51]:
np.sum(x,axis=1)

array([3, 5])

In [69]:
# Numpy arrange

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
a = np.arange(10)
print(a)
a = np.arange(10,20)
print(a)
a = np.arange(10,20,2)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[10 12 14 16 18]


In [73]:
# Stacking of arrays
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

b = b**2
print(a)
print(b)

[1 2 3 4]
[ 4  9 16 25]


In [74]:
np.stack((a,b),axis=0)

array([[ 1,  2,  3,  4],
       [ 4,  9, 16, 25]])

In [75]:
np.stack((a,b),axis=1)

array([[ 1,  4],
       [ 2,  9],
       [ 3, 16],
       [ 4, 25]])

In [76]:
a = np.stack((a,b))
print(a)

[[ 1  2  3  4]
 [ 4  9 16 25]]


In [77]:
# Transpose of a matrix

x = np.array([
    [1,1,3],
    [2,3,4],
    [1,2,5]
])

print(x)
y = x.T
print(y)

[[1 1 3]
 [2 3 4]
 [1 2 5]]
[[1 2 1]
 [1 3 2]
 [3 4 5]]


In [78]:
# Reshape a Numpy array

print(a)

[[ 1  2  3  4]
 [ 4  9 16 25]]


In [79]:
a = a.reshape((4,2))
print(a)

[[ 1  2]
 [ 3  4]
 [ 4  9]
 [16 25]]


In [80]:
a = a.reshape((8,1))
print(a)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 4]
 [ 9]
 [16]
 [25]]


In [85]:
a = a.reshape(8)
print(a)

[ 1  2  3  4  4  9 16 25]


In [86]:
a = a.reshape((4,-1)) # We want to have 4 rows but we are not sure how to calculate the columns then we specify -1
print(a)

[[ 1  2]
 [ 3  4]
 [ 4  9]
 [16 25]]


In [88]:
a = a.reshape((-1,4)) # We want to have 4 columns but we are not sure how to calculate the rows then we specify -1
print(a)

[[ 1  2  3  4]
 [ 4  9 16 25]]


In [113]:
# Iterating through the array

a = np.array([1,2,3,4,5])

for i in a:
    print(i,end=" ")

1 2 3 4 5 

## Random Module

In [89]:
a = np.arange(10)
print(a)
a = np.arange(10) + 5
print(a)

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]


In [91]:
np.random.shuffle(a)
print(a)

np.random.shuffle(a)
print(a)

np.random.shuffle(a)
print(a)

[14 10  5 12 11  9  7  6  8 13]
[ 5 12  8  6 11 14 10  7 13  9]
[10  6 14 13 11  5  8  9 12  7]


In [94]:
a = np.random.rand(2,3)
print(a)
print()
# Returns values from Standard Normal Distribution
a = np.random.randn(2,3)
print(a)

[[0.44623633 0.44745269 0.87087909]
 [0.77166616 0.54808859 0.33351734]]

[[ 4.94144840e-01 -1.07680765e+00 -8.18211272e-01]
 [-1.14391836e+00 -1.85671392e-04 -1.90116456e+00]]


In [101]:
# randint(low, high=None, size=None, dtype='l')
a = np.random.randint(5,10,3)
print(a)

[5 7 7]


In [97]:
# Randomly pick one element from an array
# choice(a, size=None, replace=True, p=None) -> Generates a random sample from a given 1-D array
element = np.random.choice([1,2,3,4,5,6,7,8,9])
print(element)

7


In [102]:
# To print the dockstring of the function
np.random.rand?

In [103]:
np.random.choice?

In [105]:
# Without seed
np.random.shuffle(a)
print(a)

np.random.shuffle(a)
print(a)

[7 7 5]
[7 5 7]


In [110]:
np.random.seed(1)
np.random.shuffle(a)
print(a)

np.random.seed(1)
np.random.shuffle(a)
print(a)

np.random.seed(1)
np.random.shuffle(a)
print(a)

np.random.seed(1)
np.random.shuffle(a)
print(a)

[7 7 5]
[7 5 7]
[7 7 5]
[7 5 7]


## Statistical Operations

In [3]:
a = np.array([
    [1,2,3,4],
    [5,6,7,8]
])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
# axis = 0 -> works along columns
# axis = 1 -> works along rows

print(np.min(a))
print(np.max(a))

print(np.min(a,axis=0))
print(np.min(a,axis=1))

1
8
[1 2 3 4]
[1 5]


In [8]:
# Mean function

b = np.array([1,2,3,4,5])
m = sum(b)/5

print(m)
print(np.mean(b))

3.0
3.0


In [9]:
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
print(np.mean(a,axis=0))
3print(np.mean(a,axis=1))

[3. 4. 5. 6.]
[2.5 6.5]


In [11]:
print(np.mean(a))

4.5


In [12]:
print(b)

[1 2 3 4 5]


In [13]:
print(np.median(b))

3.0


In [15]:
# Mean vs Average(is weighted)

arr = np.array([1,2,5,4,6,8,9])
wts = np.array([2,3,1,3,4,5,6])

print(np.average(arr,weights=wts))

5.958333333333333


In [19]:
# Standard Deviation
print(arr)
u = np.mean(arr)
std = np.sqrt(np.mean(abs(arr-u)**2))
print(std)

[1 2 5 4 6 8 9]
2.7255405754769875


In [20]:
print(np.std(arr))

2.7255405754769875


In [22]:
# Variance 
print(std**2)

print(np.var(arr))

7.428571428571428
7.428571428571429
